### ISSUE TITLE
ValueError: Expecting property name: line 6 column 1 (char 274)

### ISSUE THREAD

**Issue by khorrom-khan** [pilgun/acvtool#11]
Hi,

I am trying to instrument some apks using your tool. This is what I did so far.
1) git clone https://github.com/pilgun/acvtool
2) cd acvtool
3) pip install -e .
4) acv -h

"acv -h" command is not working properly. It's showing me the following error:

Traceback (most recent call last):
  File "/home/khorrom/.local/bin/acv", line 11, in <module>
    load_entry_point('acvtool==0.1', 'console_scripts', 'acv')()
  File "/home/khorrom/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/khorrom/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2691, in load_entry_point
    return ep.load()
  File "/home/khorrom/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2322, in load
    return self.resolve()
  File "/home/khorrom/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/khorrom/acvtool/acvtool.py", line 8, in <module>
    from smiler import smiler
  File "/home/khorrom/acvtool/smiler/smiler.py", line 9, in <module>
    from config import config
  File "/home/khorrom/acvtool/smiler/config.py", line 11, in <module>
    class config(object):
  File "/home/khorrom/acvtool/smiler/config.py", line 22, in config
    config_data = json.load(json_file)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 6 column 1 (char 274)

Please let me know if I am doing anything wrong. My operating system is ubuntu and I have java and python installed.

Thank you!

**Comment by pilgun** [comment]
Hi 👋

Setup config.json as it mentioned readme.md

**Comment by khorrom-khan** [comment]
I did that but still getting the same error.

**Comment by pilgun** [comment]
Could you try to run it like this:
‘’’python acvtool.py -h’’’

**Comment by khorrom-khan** [comment]
I tried it. Unfortunately, still didn't work and I got the following error:

Traceback (most recent call last):
  File "acvtool.py", line 8, in <module>
    from smiler import smiler
  File "/home/khorrom/acvtool/smiler/smiler.py", line 9, in <module>
    from config import config
  File "/home/khorrom/acvtool/smiler/config.py", line 11, in <module>
    class config(object):
  File "/home/khorrom/acvtool/smiler/config.py", line 22, in config
    config_data = json.load(json_file)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 6 column 1 (char 250)


My Android sdk is 29.0.2. Should I use a lower version?

**Comment by pilgun** [comment]
I believe it works with most sdk versions.

The stack trace shows that the problem is in config.json. Check every path
that you specified and the config.json for possible mistakes. You can also
post it here.

**Comment by khorrom-khan** [comment]
Thank you! acv -h is working now but instrument command is giving error. It created the  acvtool_working_dir and the .pickle file but didn't save the modified apk(apktool directory is empty).
This is the error I am getting:
`decompiled org.getdisconnected.libreipsum
parsing /home/khorrom/acvtool/acvtool_working_dir/apktool/org.getdisconnected.libreipsum/smali...
saving instrumented smali:  /home/khorrom/acvtool/acvtool_working_dir/apktool/org.getdisconnected.libreipsum/smali...
pickle file saved: /home/khorrom/acvtool/acvtool_working_dir/metadata/org.getdisconnected.libreipsum_103.pickle
instrumented
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_1217178997206961604.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 29, --version-code, 103, --version-name, 0.1.3, --no-version-vectors, -F, /tmp/APKTOOL2944119320598434162.tmp, -0, arsc, -0, META-INF/android.support.design_material.version, -0, META-INF/androidx.appcompat_appcompat.version, -0, META-INF/androidx.arch.core_core-runtime.version, -0, META-INF/androidx.asynclayoutinflater_asynclayoutinflater.version, -0, META-INF/androidx.cardview_cardview.version, -0, META-INF/androidx.coordinatorlayout_coordinatorlayout.version, -0, META-INF/androidx.core_core.version, -0, META-INF/androidx.cursoradapter_cursoradapter.version, -0, META-INF/androidx.customview_customview.version, -0, META-INF/androidx.documentfile_documentfile.version, -0, META-INF/androidx.drawerlayout_drawerlayout.version, -0, META-INF/androidx.fragment_fragment.version, -0, META-INF/androidx.interpolator_interpolator.version, -0, META-INF/androidx.legacy_legacy-support-core-ui.version, -0, META-INF/androidx.legacy_legacy-support-core-utils.version, -0, META-INF/androidx.lifecycle_lifecycle-extensions.version, -0, META-INF/androidx.lifecycle_lifecycle-livedata-core.version, -0, META-INF/androidx.lifecycle_lifecycle-livedata.version, -0, META-INF/androidx.lifecycle_lifecycle-process.version, -0, META-INF/androidx.lifecycle_lifecycle-runtime.version, -0, META-INF/androidx.lifecycle_lifecycle-service.version, -0, META-INF/androidx.lifecycle_lifecycle-viewmodel.version, -0, META-INF/androidx.loader_loader.version, -0, META-INF/androidx.localbroadcastmanager_localbroadcastmanager.version, -0, META-INF/androidx.navigation_navigation-common.version, -0, META-INF/androidx.navigation_navigation-fragment.version, -0, META-INF/androidx.navigation_navigation-runtime.version, -0, META-INF/androidx.navigation_navigation-ui.version, -0, META-INF/androidx.print_print.version, -0, META-INF/androidx.recyclerview_recyclerview.version, -0, META-INF/androidx.slidingpanelayout_slidingpanelayout.version, -0, META-INF/androidx.swiperefreshlayout_swiperefreshlayout.version, -0, META-INF/androidx.transition_transition.version, -0, META-INF/androidx.vectordrawable_vectordrawable-animated.version, -0, META-INF/androidx.vectordrawable_vectordrawable.version, -0, META-INF/androidx.versionedparcelable_versionedparcelable.version, -0, META-INF/androidx.viewpager_viewpager.version, -0, META-INF/com.google.android.material_material.version, -0, arsc, -I, /tmp/1.apk, -S, /home/khorrom/acvtool/acvtool_working_dir/apktool/org.getdisconnected.libreipsum/res, -M, /home/khorrom/acvtool/acvtool_working_dir/apktool/org.getdisconnected.libreipsum/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:492)
	at brut.androlib.Androlib.buildResources(Androlib.java:426)
	at brut.androlib.Androlib.build(Androlib.java:305)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_1217178997206961604.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 29, --version-code, 103, --version-name, 0.1.3, --no-version-vectors, -F, /tmp/APKTOOL2944119320598434162.tmp, -0, arsc, -0, META-INF/android.support.design_material.version, -0, META-INF/androidx.appcompat_appcompat.version, -0, META-INF/androidx.arch.core_core-runtime.version, -0, META-INF/androidx.asynclayoutinflater_asynclayoutinflater.version, -0, META-INF/androidx.cardview_cardview.version, -0, META-INF/androidx.coordinatorlayout_coordinatorlayout.version, -0, META-INF/androidx.core_core.version, -0, META-INF/androidx.cursoradapter_cursoradapter.version, -0, META-INF/androidx.customview_customview.version, -0, META-INF/androidx.documentfile_documentfile.version, -0, META-INF/androidx.drawerlayout_drawerlayout.version, -0, META-INF/androidx.fragment_fragment.version, -0, META-INF/androidx.interpolator_interpolator.version, -0, META-INF/androidx.legacy_legacy-support-core-ui.version, -0, META-INF/androidx.legacy_legacy-support-core-utils.version, -0, META-INF/androidx.lifecycle_lifecycle-extensions.version, -0, META-INF/androidx.lifecycle_lifecycle-livedata-core.version, -0, META-INF/androidx.lifecycle_lifecycle-livedata.version, -0, META-INF/androidx.lifecycle_lifecycle-process.version, -0, META-INF/androidx.lifecycle_lifecycle-runtime.version, -0, META-INF/androidx.lifecycle_lifecycle-service.version, -0, META-INF/androidx.lifecycle_lifecycle-viewmodel.version, -0, META-INF/androidx.loader_loader.version, -0, META-INF/androidx.localbroadcastmanager_localbroadcastmanager.version, -0, META-INF/androidx.navigation_navigation-common.version, -0, META-INF/androidx.navigation_navigation-fragment.version, -0, META-INF/androidx.navigation_navigation-runtime.version, -0, META-INF/androidx.navigation_navigation-ui.version, -0, META-INF/androidx.print_print.version, -0, META-INF/androidx.recyclerview_recyclerview.version, -0, META-INF/androidx.slidingpanelayout_slidingpanelayout.version, -0, META-INF/androidx.swiperefreshlayout_swiperefreshlayout.version, -0, META-INF/androidx.transition_transition.version, -0, META-INF/androidx.vectordrawable_vectordrawable-animated.version, -0, META-INF/androidx.vectordrawable_vectordrawable.version, -0, META-INF/androidx.versionedparcelable_versionedparcelable.version, -0, META-INF/androidx.viewpager_viewpager.version, -0, META-INF/com.google.android.material_material.version, -0, arsc, -I, /tmp/1.apk, -S, /home/khorrom/acvtool/acvtool_working_dir/apktool/org.getdisconnected.libreipsum/res, -M, /home/khorrom/acvtool/acvtool_working_dir/apktool/org.getdisconnected.libreipsum/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:456)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_1217178997206961604.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 29, --version-code, 103, --version-name, 0.1.3, --no-version-vectors, -F, /tmp/APKTOOL2944119320598434162.tmp, -0, arsc, -0, META-INF/android.support.design_material.version, -0, META-INF/androidx.appcompat_appcompat.version, -0, META-INF/androidx.arch.core_core-runtime.version, -0, META-INF/androidx.asynclayoutinflater_asynclayoutinflater.version, -0, META-INF/androidx.cardview_cardview.version, -0, META-INF/androidx.coordinatorlayout_coordinatorlayout.version, -0, META-INF/androidx.core_core.version, -0, META-INF/androidx.cursoradapter_cursoradapter.version, -0, META-INF/androidx.customview_customview.version, -0, META-INF/androidx.documentfile_documentfile.version, -0, META-INF/androidx.drawerlayout_drawerlayout.version, -0, META-INF/androidx.fragment_fragment.version, -0, META-INF/androidx.interpolator_interpolator.version, -0, META-INF/androidx.legacy_legacy-support-core-ui.version, -0, META-INF/androidx.legacy_legacy-support-core-utils.version, -0, META-INF/androidx.lifecycle_lifecycle-extensions.version, -0, META-INF/androidx.lifecycle_lifecycle-livedata-core.version, -0, META-INF/androidx.lifecycle_lifecycle-livedata.version, -0, META-INF/androidx.lifecycle_lifecycle-process.version, -0, META-INF/androidx.lifecycle_lifecycle-runtime.version, -0, META-INF/androidx.lifecycle_lifecycle-service.version, -0, META-INF/androidx.lifecycle_lifecycle-viewmodel.version, -0, META-INF/androidx.loader_loader.version, -0, META-INF/androidx.localbroadcastmanager_localbroadcastmanager.version, -0, META-INF/androidx.navigation_navigation-common.version, -0, META-INF/androidx.navigation_navigation-fragment.version, -0, META-INF/androidx.navigation_navigation-runtime.version, -0, META-INF/androidx.navigation_navigation-ui.version, -0, META-INF/androidx.print_print.version, -0, META-INF/androidx.recyclerview_recyclerview.version, -0, META-INF/androidx.slidingpanelayout_slidingpanelayout.version, -0, META-INF/androidx.swiperefreshlayout_swiperefreshlayout.version, -0, META-INF/androidx.transition_transition.version, -0, META-INF/androidx.vectordrawable_vectordrawable-animated.version, -0, META-INF/androidx.vectordrawable_vectordrawable.version, -0, META-INF/androidx.versionedparcelable_versionedparcelable.version, -0, META-INF/androidx.viewpager_viewpager.version, -0, META-INF/com.google.android.material_material.version, -0, arsc, -I, /tmp/1.apk, -S, /home/khorrom/acvtool/acvtool_working_dir/apktool/org.getdisconnected.libreipsum/res, -M, /home/khorrom/acvtool/acvtool_working_dir/apktool/org.getdisconnected.libreipsum/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:450)
	... 6 more

built
Traceback (most recent call last):
  File "/home/khorrom/.local/bin/acv", line 11, in <module>
    load_entry_point('acvtool', 'console_scripts', 'acv')()
  File "/home/khorrom/acvtool/acvtool.py", line 217, in main
    run_actions(parser, args)
  File "/home/khorrom/acvtool/acvtool.py", line 52, in run_actions
    mem_stats=args.memstats)
  File "/home/khorrom/acvtool/smiler/instrumenting/utils.py", line 107, in wrapper
    result = method(*args, **kwargs)
  File "/home/khorrom/acvtool/smiler/smiler.py", line 186, in instrument_apk
    sign_align_apk(instrumented_package_path, instrumented_apk_path)
  File "/home/khorrom/acvtool/smiler/smiler.py", line 277, in sign_align_apk
    request_pipe(align_cmd)
  File "/home/khorrom/acvtool/smiler/smiler.py", line 47, in request_pipe
    Out: %s\nError: %s" % (out, err))
Exception: ----------------------------------------------------
Out: 
Error: Unable to open '/home/khorrom/acvtool/acvtool_working_dir/org.getdisconnected.libreipsum_103.apk' as zip archive
`

**Comment by pilgun** [comment]
This can be either a problem with apktool or acvtool.
If you can repackage this app with apktool only (just disassemble and assemble again), then the problem may be caused by acvtool.

**Comment by khorrom-khan** [comment]
Thank you so much. The problem was with the apktool. Worked with version  2.4.1.
