### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by msteeleusmc** [pilgun/acvtool#16]
So now that the acvtool is installed correctly, I get the following error when trying to instrument.

Traceback (most recent call last):
  File "C:\Python27\Scripts\acv-script.py", line 11, in <module>
    load_entry_point('acvtool', 'console_scripts', 'acv')()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\acvtool-master\acvtool.py", line 8, in <module>
    from smiler import smiler
  File "c:\acvtool-master\smiler\smiler.py", line 9, in <module>
    from config import config
  File "c:\acvtool-master\smiler\config.py", line 11, in <module>
    class config(object):
  File "c:\acvtool-master\smiler\config.py", line 22, in config
    config_data = json.load(json_file)
  File "c:\python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "c:\python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "c:\python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid \escape: line 2 column 14 (char 15)

**Comment by pilgun** [comment]
Please update the config json file according to readme

**Comment by msteeleusmc** [comment]
It is.

{
  "AAPT": "C:\Users\micha\AppData\Local\Android\Sdk\build-tools\25.0.1\aapt.exe",
  "ZIPALIGN": "C:\Users\micha\AppData\Local\Android\Sdk\build-tools\25.0.1\zipalign.exe",
  "ADB": "C:\Users\micha\AppData\Local\Android\Sdk\platform-tools\adb.exe",
  "APKSIGNER": "C:\Users\micha\AppData\Local\Android\Sdk\build-tools\24.0.3\apksinger.bat"
}

**Comment by msteeleusmc** [comment]
I get the error trying 
"acv instrument C:\Users\micha\AndroidStudioProjects\wifisetup\wifisetup\app\build\outputs\apk\debug\app-debug.apk"

**Comment by pilgun** [comment]
Try to put double backslashes in config json as it was the example \\

**Comment by msteeleusmc** [comment]
Thank you. I realized that while using Windows, I extracted the file which made acvtool-master into my C:\ directory. I then updated the config file first. Then I did the 'pip install -e .' and everything seems to be working now regarding this issue.
