### ISSUE TITLE
acv start

### ISSUE THREAD

**Issue by msteeleusmc** [pilgun/acvtool#17]
I am using a Windows OS. To instrument I used **acv instrument C:\Users\micha\AndroidStudioProjects\wifisetup\wifisetup\app\build\outputs\apk\debug\app-debug.apk**

Then to install I has to use  acv install C:\Users\micha\AndroidStudioProjects\wifisetup\wifisetup\app\build\outputs\apk\debug\app-debug.apk

Then to start acv start nl.eventinfra.wifisetup 

I get the following error:

Operation not allowed: java.lang.SecurityException: Can't change android.permission.READ_EXTERNAL_STORAGE. It is required by the application
Operation not allowed: java.lang.SecurityException: Can't change android.permission.WRITE_EXTERNAL_STORAGE. It is required by the application
Press Ctrl+C to finish ...
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{nl.eventinfra.wifisetup/tool.acv.AcvInstrumentation}
INSTRUMENTATION_STATUS_CODE: -1
android.util.AndroidException: INSTRUMENTATION_FAILED: nl.eventinfra.wifisetup/tool.acv.AcvInstrumentation
        at com.android.commands.am.Am.runInstrument(Am.java:977)
        at com.android.commands.am.Am.onRun(Am.java:317)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
        at com.android.commands.am.Am.main(Am.java:97)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)

**Comment by pilgun** [comment]
Make sure you install the instrumented version of app.
It is usually located in the acvtool_working_dir and its name starts from
instr_...

**Comment by msteeleusmc** [comment]
Ok, so that is not creating.

**Comment by msteeleusmc** [comment]
This is at instrumentation

PS C:\Users\micha> acv instrument C:\Users\micha\AndroidStudioProjects\wifisetup\wifisetup\app\build\outputs\apk\debug\app-debug.apk
The working directory exists and may contain data: C:\Users\micha\acvtool\acvtool_working_dir
Overwrite (y/n)? y
decompiled nl.eventinfra.wifisetup
parsing C:\Users\micha\acvtool\acvtool_working_dir\apktool\nl.eventinfra.wifisetup\smali...
saving instrumented smali:  C:\Users\micha\acvtool\acvtool_working_dir\apktool\nl.eventinfra.wifisetup\smali...
pickle file saved: C:\Users\micha\acvtool\acvtool_working_dir\metadata\app-debug.pickle
instrumented
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\micha\AppData\Local\Temp\brut_util_Jar_938436055564660955.tmp, p, --forced-package-id, 127, --min-sdk-version, 18, --target-sdk-version, 28, --version-code, 20191205, --version-name, 0.31, --no-version-vectors, -F, C:\Users\micha\AppData\Local\Temp\APKTOOL5058766867846773367.tmp, -0, arsc, -0, der, -0, META-INF/androidx.versionedparcelable_versionedparcelable.version, -0, META-INF/android.arch.lifecycle_runtime.version, -0, META-INF/androidx.core_core.version, -0, arsc, -I, C:\Users\micha\AppData\Local\Temp\1.apk, -S, C:\Users\micha\acvtool\acvtool_working_dir\apktool\nl.eventinfra.wifisetup\res, -M, C:\Users\micha\acvtool\acvtool_working_dir\apktool\nl.eventinfra.wifisetup\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:492)
        at brut.androlib.Androlib.buildResources(Androlib.java:426)
        at brut.androlib.Androlib.build(Androlib.java:305)
        at brut.androlib.Androlib.build(Androlib.java:270)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\micha\AppData\Local\Temp\brut_util_Jar_938436055564660955.tmp, p, --forced-package-id, 127, --min-sdk-version, 18, --target-sdk-version, 28, --version-code, 20191205, --version-name, 0.31, --no-version-vectors, -F, C:\Users\micha\AppData\Local\Temp\APKTOOL5058766867846773367.tmp, -0, arsc, -0, der, -0, META-INF/androidx.versionedparcelable_versionedparcelable.version, -0, META-INF/android.arch.lifecycle_runtime.version, -0, META-INF/androidx.core_core.version, -0, arsc, -I, C:\Users\micha\AppData\Local\Temp\1.apk, -S, C:\Users\micha\acvtool\acvtool_working_dir\apktool\nl.eventinfra.wifisetup\res, -M, C:\Users\micha\acvtool\acvtool_working_dir\apktool\nl.eventinfra.wifisetup\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:456)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\micha\AppData\Local\Temp\brut_util_Jar_938436055564660955.tmp, p, --forced-package-id, 127, --min-sdk-version, 18, --target-sdk-version, 28, --version-code, 20191205, --version-name, 0.31, --no-version-vectors, -F, C:\Users\micha\AppData\Local\Temp\APKTOOL5058766867846773367.tmp, -0, arsc, -0, der, -0, META-INF/androidx.versionedparcelable_versionedparcelable.version, -0, META-INF/android.arch.lifecycle_runtime.version, -0, META-INF/androidx.core_core.version, -0, arsc, -I, C:\Users\micha\AppData\Local\Temp\1.apk, -S, C:\Users\micha\acvtool\acvtool_working_dir\apktool\nl.eventinfra.wifisetup\res, -M, C:\Users\micha\acvtool\acvtool_working_dir\apktool\nl.eventinfra.wifisetup\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:450)
        ... 6 more

built
Traceback (most recent call last):
  File "C:\Python27\Scripts\acv-script.py", line 11, in <module>
    load_entry_point('acvtool', 'console_scripts', 'acv')()
  File "c:\acvtool-master\acvtool.py", line 217, in main
    run_actions(parser, args)
  File "c:\acvtool-master\acvtool.py", line 52, in run_actions
    mem_stats=args.memstats)
  File "c:\acvtool-master\smiler\instrumenting\utils.py", line 107, in wrapper
    result = method(*args, **kwargs)
  File "c:\acvtool-master\smiler\smiler.py", line 186, in instrument_apk
    sign_align_apk(instrumented_package_path, instrumented_apk_path)
  File "c:\acvtool-master\smiler\smiler.py", line 277, in sign_align_apk
    request_pipe(align_cmd)
  File "c:\acvtool-master\smiler\smiler.py", line 47, in request_pipe
    Out: %s\nError: %s" % (out, err))
Exception: ----------------------------------------------------
Out:
Error: Unable to open 'C:\Users\micha\acvtool\acvtool_working_dir\app-debug.apk' as zip archive

**Comment by pilgun** [comment]
I have checked nl.eventinfra.wifisetup app you mentioned.

Unfortunately, current version of acvtool breaks the app. I have an updated version that worked on this app. However, I am not yet ready to roll it out nor provide the update date. So stay tuned.

**Comment by msteeleusmc** [comment]
Is there some guidance on what kind of parameters I should stay within to run this tool with android applications on Windows?

**Comment by pilgun** [comment]
no specific parameters for any OS

you can try to instrument default fdroid app to make sure that acvtool works on your computer https://f-droid.org/F-Droid.apk

**Comment by msteeleusmc** [comment]
It seems to not happen to every application. Is this the default error when it will not open at all? Because I have other applications that are similar that run.
