### ISSUE TITLE
Test Execution crashes when using instrumented apk

### ISSUE THREAD

**Issue by jc1850** [pilgun/acvtool#20]
I am attempting to use acvtool to find the coverage of some tests on the Antennapod open source application. I can run acvtool and measure the coverage of manual input however not instrumented tests. I have installed the instrumented version of the application and the test package. When I run the command:

`adb shell am instrument -w de.test.antennapod/androidx.test.runner.AndroidJUnitRunner`

I get the error message:

```
java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{de.test.antennapod/androidx.test.runner.AndroidJUnitRunner} from pid=7420, uid=7420 not allowed because package de.test.antennapod does not have a signature matching the target de.danoeh.antennapod.debug
	at android.os.Parcel.createException(Parcel.java:2071)
INSTRUMENTATION_STATUS: Error=Permission Denial: starting instrumentation ComponentInfo{de.test.antennapod/androidx.test.runner.AndroidJUnitRunner} from pid=7420, uid=7420 not allowed because package de.test.antennapod does not have a signature matching the target de.danoeh.antennapod.debug
	at android.os.Parcel.readException(Parcel.java:2039)
INSTRUMENTATION_STATUS: id=ActivityManagerService
	at android.os.Parcel.readException(Parcel.java:1987)INSTRUMENTATION_STATUS_CODE: -1
	at android.app.IActivityManager$Stub$Proxy.startInstrumentation(IActivityManager.java:5441)

	at com.android.commands.am.Instrument.run(Instrument.java:512)
	at com.android.commands.am.Am.runInstrument(Am.java:196)
	at com.android.commands.am.Am.onRun(Am.java:80)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:56)
	at com.android.commands.am.Am.main(Am.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.startInstrumentation(ActivityManagerService.java:15744)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2350)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2741)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
```

**Comment by jc1850** [comment]
I sinced solved this by signing the test package apk. I had to do this manually however as using acv sign crashed, giving this message:

```
Traceback (most recent call last):
  File "/home/james/.local/bin/acv", line 11, in <module>
    load_entry_point('acvtool', 'console_scripts', 'acv')()
  File "/home/james/acvtool/acvtool.py", line 217, in main
    run_actions(parser, args)
  File "/home/james/acvtool/acvtool.py", line 90, in run_actions
    smiler.sign_align_apk(args.apk_path, "{0}.signed.apk".format(args.apk_path))
  File "/home/james/acvtool/smiler/smiler.py", line 277, in sign_align_apk
    request_pipe(align_cmd)
  File "/home/james/acvtool/smiler/smiler.py", line 47, in request_pipe
    Out: %s\nError: %s" % (out, err))
Exception: ----------------------------------------------------
Out: 
Error: 
```
