### ISSUE TITLE
acv instrument doesn't work 

### ISSUE THREAD

**Issue by MicheleDaniele** [pilgun/acvtool#34]
Good morning, I am a _macOS user with Intel core i9 operating system_.
I've been trying to use your tool with various different applications for days now but whatever the application, even the most trivial I can't instrument it. 
After running the command 
`acv instrument /path/to/file.apk`, I sit on hold for hours never receiving anything.
**How come I can't instrument the apk?**
All your prerequisites are met:
- Java version 1.8.
- Android SDK.
- Python version 2.7.

<img width="1653" alt="Screenshot 2023-08-19 alle 11 24 49" src="https://github.com/pilgun/acvtool/assets/101891118/69dec236-429b-497e-975a-50af4c8a006e">

**Comment by pilgun** [comment]
Hi,

I guess it's a python issues. Could you try launching the python script
directly?

```
python acvtool.py instrument ...
```

**Comment by MicheleDaniele** [comment]
Thank you for your immediate response. 
Unfortunately, however, I just tried but I keep getting nothing.

**Comment by pilgun** [comment]
It's unusual, you may can try first

python acvtool.py -h

If it prints fine maybe check one more time the config json and that
apktool and java actually can run.

**Comment by MicheleDaniele** [comment]
Good morning, fortunately I was able to start the 'acv instrument' command. The trick was to start the tool via the teminal of the PyCharm CE app, strange but true.
Now unfortunately I get one more problem: 
`**Unable to open '/Users/user/acvtool/acvtool_working_dir/pl.sanszo.pcis_2.apk' as zipper archive**`

I leave the full error trace below.
```
acv instrument /Users/user/Desktop/single-dex/pl.sanszo.pcis_2.apk
Working directory exists and may contain data: /Users/user/acvtool/acvtool_working_dir
Overwrite (y/n)? y
Exception in "main" thread brut.androlib.AndrolibException: Invalid chunk type: expected=0x00000200, got=0x00000206
        a brut.androlib.res.decoder.ARSCDecoder.checkChunkType(ARSCDecoder.java:542)
        a brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:88)
        a brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
        a brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
        a brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:786)
        a brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:123)
        a brut.androlib.res.data.ResTable.getPackage(ResTable.java:84)
        a brut.androlib.res.data.ResTable.getResSpec(ResTable.java:67)
        a brut.androlib.res.data.ResTable.getResSpec(ResTable.java:63)
        a brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:62)
        a brut.androlib.res.data.value.ResReferenceValue.referentIsNull(ResReferenceValue.java:73)
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:49)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:742)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:263)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:129)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
        at brut.apktool.Main.cmdDecode(Main.java:170)
        a brut.apktool.Main.main(Main.java:76)

The execution failed!
decompiled pl.sanszo.pcis
parsing /Users/user/acvtool/acvtool_working_dir/apktool/pl.sanszo.pcis/smali...
saved instrumented smali: /Users/user/acvtool/acvtool_working_dir/apktool/pl.sanszo.pcis/smali...
saved pickle file: /Users/user/acvtool/acvtool_working_dir/metadata/pl.sanszo.pcis_2.pickle
instrumented
brut.directory.PathNotExist: apktool.yml

built
Traceback (last call):
  File "/usr/local/Caskroom/miniconda/base/envs/penv27java18/bin/acv", line 11, in <module>
    load_entry_point('acvtool', 'console_scripts', 'acv')()
  File "/Users/user/Desktop/acvtool/acvtool.py", line 217, in main
    run_actions(parser, args)
  File "/Users/user/Desktop/acvtool/acvtool.py," line 52, in run_actions
    mem_stats=args.memstats)
  File "/Users/user/Desktop/acvtool/smiler/instrumenting/utils.py", line 107, in wrapper
    result = method(*args, **kwargs)
  File "/Users/user/Desktop/acvtool/smiler/smiler.py", line 186, in instrument_apk
    sign_align_apk(instrumented_package_path, instrumented_apk_path)
  File "/Users/user/Desktop/acvtool/smiler/smiler.py", line 277, in sign_align_apk
    request_pipe(align_cmd)
  File "/Users/user/Desktop/acvtool/smiler/smiler.py", line 47, in request_pipe
    Out: %sEntry in error: %s" % (out, err))
Exception: ----------------------------------------------------
Out: 
Error: Unable to open '/Users/user/acvtool/acvtool_working_dir/pl.sanszo.pcis_2.apk' as zipper archive
```

I apologize again for the trouble and thank you in advance.

**Comment by pilgun** [comment]
Could you please try directly from the `acvtool` directory in the terminal
```
> python acvtool.py instrument
/Users/user/Desktop/single-dex/pl.sanszo.pcis_2.apk
```

And please check the python version `> python -V` should be 2.7+

**Comment by MicheleDaniele** [comment]
I've already tried but I receive the same error :(

**Comment by pilgun** [comment]
I see you are using an environment: 'Caskroom/miniconda/base/envs/penv27java18'. It should not be an issue, but maybe you could call directly the python2.7 instance and also put arguments for the working directory. The error says apktool can't find the apktool.yml file. This could mean that apktool probably runs over wrong directory because usually apktool.yml is always there.
```acv_repo:> /usr/bin/python2 acvtool.py instrument /Users/user/Desktop/single-dex/pl.sanszo.pcis_2.apk --wd wd```

The `--wd` option is for the path to the working directory.

**Comment by MicheleDaniele** [comment]
Just tried but unfortunately I always get the same error:
/usr/local/bin/python2 acvtool.py instrument /Users/user/Desktop/single-dex/ardash.lato_1001006.apk --wd wd ─╯

Working directory exists and may contain data: wd
Overwrite (y/n)? y
```
Exception in "main" thread brut.androlib.AndrolibException: Invalid chunk type: expected=0x00000200, got=0x00000206
	a brut.androlib.res.decoder.ARSCDecoder.checkChunkType(ARSCDecoder.java:542)
	a brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:88)
	a brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
	a brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
	a brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:786)
	a brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:123)
	a brut.androlib.res.data.ResTable.getPackage(ResTable.java:84)
	a brut.androlib.res.data.ResTable.getResSpec(ResTable.java:67)
	a brut.androlib.res.data.ResTable.getResSpec(ResTable.java:63)
	a brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:62)
	a brut.androlib.res.data.value.ResReferenceValue.referentIsNull(ResReferenceValue.java:73)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:49)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:742)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:263)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:129)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	a brut.apktool.Main.main(Main.java:76)

The execution failed!
decompiled ardash.side
parsing wd/apktool/ardash.side/smali...
saved instrumented smali: wd/apktool/ardash.side/smali...
saved pickle file: wd/metadata/ardash.side_1001006.pickle
instrumented
brut.directory.PathNotExist: apktool.yml

built
Traceback (last call):
  "acvtool.py" file, line 220, in <module>.
    main()
  File "acvtool.py", line 217, in main
    run_actions(parser, args)
  File "acvtool.py," line 52, in run_actions
    mem_stats=args.memstats)
  File "/Users/user/Desktop/acvtool/smiler/instrumenting/utils.py", line 107, in wrapper
    result = method(*args, **kwargs)
  File "/Users/user/Desktop/acvtool/smiler/smiler.py", line 186, in instrument_apk
    sign_align_apk(instrumented_package_path, instrumented_apk_path)
  File "/Users/user/Desktop/acvtool/smiler/smiler.py", line 277, in sign_align_apk
    request_pipe(align_cmd)
  File "/Users/user/Desktop/acvtool/smiler/smiler.py", line 47, in request_pipe
    Out: %sEntry in error: %s" % (out, err))
Exception: ----------------------------------------------------
Out:
Error: Unable to open 'wd/ardash.lato_1001006.apk' as a zip archive 
```

Sorry to be wasting your time but I am very curious to try it out
