### ISSUE TITLE
How to fill in commands in Windows

### ISSUE THREAD

**Issue by RayPengzhihui** [pilgun/acvtool#43]
Execute the command in my D: \ \ workspace \ \ acvtool master directory
I entered
acv instrument ‪‪D:\\workspace\\acvtool-master\\iBiliPlayer-bili.apk --wd wd
Or perhaps
acv instrument ‪‪D:\workspace\acvtool-master\iBiliPlayer-bili.apk --wd wd   
Or perhaps
acv instrument ‪iBiliPlayer-bili.apk --wd wd
All errors are W ziparchive: Unable to open '‪ acvtool \ iBiliPlayer bili. apk': No such file or directory
‪acvtool\iBiliPlayer-bili.apk: error: failed opening zip: I/O error.

**Comment by RayPengzhihui** [comment]
`PS D:\workspace\acvtool-master> acv instrument ‪acvtool\iBiliPlayer-bili.apk --wd wd                        
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\zhihui.peng\AppData\Local\Programs\Python\Python312\Scripts\acv.exe\__main__.py", line 7, in <module>
  File "D:\workspace\acvtool-master\acvtool\acvtool.py", line 89, in main
    run_actions(parser, args)
  File "D:\workspace\acvtool-master\acvtool\acvtool.py", line 27, in run_actions
    acv.instrument(args)
  File "D:\workspace\acvtool-master\acvtool\smiler\acv.py", line 26, in instrument
    package, apk_path, pickle_path = smiler.instrument_apk(
                                     ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\acvtool-master\acvtool\smiler\instrumenting\utils.py", line 141, in wrapper
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\acvtool-master\acvtool\smiler\smiler.py", line 269, in instrument_apk
    package = get_apk_properties(apk_path).package
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\acvtool-master\acvtool\smiler\smiler.py", line 72, in get_apk_properties
    out = terminal.request_pipe(info_cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\acvtool-master\acvtool\smiler\operations\terminal.py", line 12, in request_pipe
    raise Exception("----------------------------------------------------\n\
Exception: ----------------------------------------------------
Out:
Error: 08-27 16:15:03.625 30156 23360 W ziparchive: Unable to open '‪acvtool\iBiliPlayer-bili.apk': No such file or directory
‪acvtool\iBiliPlayer-bili.apk: error: failed opening zip: I/O error.
`

**Comment by pilgun** [comment]
Hey @RayPengzhihui 
Sorry it did not work for you, for some reason paths are messed up on Windows. I hope to find a minute to fix it by the weekend. Meanwhile, could you try without 'wd' parameter?

**Comment by RayPengzhihui** [comment]
Hey @pilgun 
Thank you very much for your answer, but I still get the same error message without '--wd wd'
error  like this
`Error: 08-29 13:43:54.175 28868 13068 W ziparchive: Unable to open '‪‪D:\\workspace\\acvtool-master\\ByteApp_offline2develop_debug_v5.0.6-launcher_20240702_webview.apk': Invalid argument
‪‪D:\\workspace\\acvtool-master\\ByteApp_offline2develop_debug_v5.0.6-launcher_20240702_webview.apk: error: failed opening zip: I/O error.`

**Comment by pilgun** [comment]
Hey @RayPengzhihui
I have double checked on Windows, it's always working. Could you make sure you have put correct path for your app?

**Comment by RayPengzhihui** [comment]
> Hey @RayPengzhihui I have double checked on Windows, it's always working. Could you make sure you have put correct path for your app?

Hey @pilgun

**Comment by RayPengzhihui** [comment]
Hey @pilgun 
How to solve the issue of saving when I install APK
 acv install .\wd\instr_com.t.store.apk
`installing instr_com.t.store.apk
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\zhihui.peng\AppData\Local\Programs\Python\Python312\Scripts\acv.exe\__main__.py", line 7, in <module>
  File "D:\workspace\acvtool-master\acvtool\acvtool.py", line 89, in main
    run_actions(parser, args)
  File "D:\workspace\acvtool-master\acvtool\acvtool.py", line 29, in run_actions
    acv.install(args)
  File "D:\workspace\acvtool-master\acvtool\smiler\acv.py", line 50, in install
    smiler.install(args.apk_path)
  File "D:\workspace\acvtool-master\acvtool\smiler\smiler.py", line 37, in install
    out = terminal.request_pipe(cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\acvtool-master\acvtool\smiler\operations\terminal.py", line 12, in request_pipe
    raise Exception("----------------------------------------------------\n\
Exception: ----------------------------------------------------
Out: Performing Streamed Install

Error: adb: failed to install .\wd\instr_com.t.store.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Existing package com.t.store signatures do not match newer version; ignoring!]
`

**Comment by pilgun** [comment]
Do uninstall first
