### ISSUE TITLE
INSTRUMENTATION_CODE=0 during "acv start <package-name>" 

### ISSUE THREAD

**Issue by rakin000** [pilgun/acvtool#46]
I've followed [this](https://www.youtube.com/watch?v=xyaR4Ivrij0). But when I execute the   `acv start com.aimp.player` , I get the following error. 

```bin/bash

> acv start com.aimp.player

Press Ctrl+C to finish ...
INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0
```

**Comment by pilgun** [comment]
Hey Rakin000, the video is too old, no need to run `acv start` anymore.

Follow the new workflow
```
$ acv activate com.gnsdm.snake
$ acv snap com.gnsdm.snake
$ acv cover-pickles com.gnsdm.snake
$ acv report com.gnsdm.snake
```

**Comment by srbd2024** [comment]
> Hey Rakin000, the video is too old, no need to run `acv start` anymore.
> 
> Follow the new workflow
> 
> ```
> $ acv activate com.gnsdm.snake
> $ acv snap com.gnsdm.snake
> $ acv cover-pickles com.gnsdm.snake
> $ acv report com.gnsdm.snake
> ```

Somehow I am not getting the "pickle" files after `acv snap com.gnsdm.snake` and `acv cover-pickles com.gnsdm.snake` gives following error 
```
Traceback (most recent call last):
  File "~/miniconda3/bin/acv", line 33, in <module>
    sys.exit(load_entry_point('acvtool', 'console_scripts', 'acv')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/Desktop/acvtool/acvtool/acvtool.py", line 89, in main
    run_actions(parser, args)
  File "~/Desktop/acvtool/acvtool/acvtool.py", line 47, in run_actions
    acv.cover_pickles(args)
  File "~/Desktop/acvtool/acvtool/smiler/acv.py", line 97, in cover_pickles
    coverage.cover_pickles(wd)
  File "~/Desktop/acvtool/acvtool/smiler/operations/coverage.py", line 23, in cover_pickles
    pkl_path = covered_pkls[dex] if covered_pkls else pkls[dex]
                                                      ~~~~^^^^^
KeyError: 1

```

**Comment by pilgun** [comment]
Perhaps you could remove everything from ~/acvtool/acvtool_working_dir/ and try again?

**Comment by srbd2024** [comment]
> Perhaps you could remove everything from ~/acvtool/acvtool_working_dir/ and try again?

Yes, I've tried that. Also I tried after reinstalling acvtool but no success. Still got the same problem. 

Actually the problem was that it needs `pickles` files from instrumentation process. `snap`, `cover-pickles` and `report` sub-commands are needed to be run on the same working directory. 

Thanks a lot.
